const SCREEN_NAME = {
  // Root screens
  HOME: 'HOME',
  USER_DETAIL: 'USER_DETAIL',
  NEW_POST: 'NEW_POST',
  LIKE: 'LIKE',
  SEARCH: 'SEARCH',
  // Other screens
  ROOT: 'ROOT',
  IMAGE_VIEWER: 'IMAGE_VIEWER',
  LOGIN: 'LOGIN',
  SWITCH_ACCOUNT: 'SWITCH_ACCOUNT',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  LOADING_INFO: 'LOADING_INFO',
  SETTINGS: 'SETTINGS',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  NEW_POST_MODAL: 'NEW_POST_MODAL',
} as const;

export default SCREEN_NAME;
