const ROOT_SCREEN = {
  HOME: 'HOME',
  USER_DETAIL: 'USER_DETAIL',
  NEW_POST: 'NEW_POST',
  LIKE: 'LIKE',
  SEARCH: 'SEARCH',
};

const SCREEN_NAME = {
  IMAGE_VIEWER: 'IMAGE_VIEWER',
  POST_DETAIL: 'POST_DETAIL',
  NEW_POST_MODAL: 'NEW_POST_MODAL',
  ROOT: 'ROOT',
};

export {ROOT_SCREEN, SCREEN_NAME};
