const ROOT_SCREEN = {
  HOME: 'HOME',
  USER_DETAIL: 'USER_DETAIL',
  NEWS: 'NEWS',
  LIKE: 'LIKE',
  SEARCH: 'SEARCH',
};

const SCREEN_NAME = {
  IMAGE_VIEWER: 'IMAGE_VIEWER',
  POST_DETAIL: 'POST_DETAIL',
};

export {ROOT_SCREEN, SCREEN_NAME};
