// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	// Create a new user
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Create a new user profile
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	// Delete a user by ID
	DeleteUser(ctx context.Context, id int64) error
	// Delete a user profile by ID
	DeleteUserProfile(ctx context.Context, id int64) error
	// Get a list of all users
	GetListUser(ctx context.Context, arg GetListUserParams) ([]User, error)
	// Get a user by ID
	GetUserById(ctx context.Context, id int64) (User, error)
	// Get a user by ID for update
	GetUserForUpdate(ctx context.Context, id int64) (User, error)
	// Get a user profile by ID
	GetUserProfileById(ctx context.Context, id int64) (UserProfile, error)
	// Update a user's information
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Update a user's profile
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
