// Actions
export const APP = {
  CLEAR_REDUCER: 'APP/CLEAR_REDUCER',
  CHANGE_LANGUAGE: 'APP/CHANGE_LANGUAGE',
  SAVE_DOMAIN: 'APP/SAVE_DOMAIN',
  SAVE_DEVICE_INFO: 'APP/SAVE_DEVICE_INFO',
  SAVE_SETTING: 'APP/SAVE_SETTING',
  START_APPLICATION: 'APP/START_APPLICATION',
};

export const AUTH = {
  LOGIN: 'AUTH/LOGIN',
  REGISTER: 'AUTH/REGISTER',
  LOGOUT: 'AUTH/LOGOUT',
  SAVE_TOKEN: 'AUTH/SAVE_TOKEN',
  ADD_ACCOUNT_INFO: 'AUTH/ADD_ACCOUNT_INFO',
};

export const USER = {
  GET_USER_INFO: 'USER/GET_USER_INFO',
  UPDATE_INFO: 'USER/UPDATE_INFO',
};

export const LOADING = {
  FETCH: {
    FETCHING: 'LOADING/FETCH_FETCHING',
    NON_FETCHING: 'LOADING/FETCH_NON_FETCHING',
  },
  DIALOG: {
    SHOW: 'LOADING/DIALOG_SHOW',
    HIDE: 'LOADING/DIALOG_HIDE',
  },
};

export const ERROR = {
  DIALOG: {
    SHOW: 'ERROR/DIALOG_SHOW',
    HIDE: 'ERROR/DIALOG_HIDE',
  },
};

export const CONNECTIVITY = {
  APP_CONNECTIVITY_CHANGE: 'CONNECTIVITY/APP_CONNECTIVITY_CHANGE',
};
